classdef MeshWriter
% MESHWRITER Export structured surface meshes to various formats.
%
% Supported exports:
%   - LaWGS / PanAir WGS
%   - VTK legacy ASCII unstructured grid
%   - ASCII STL
%   - CSV node dump
%
% Expected mesh struct fields from geom.NURBSSurface.isoMesh():
%   X, Y, Z           [nu x nv]
%   nu, nv
%   normals           [nu x nv x 3] (optional)
%   u, v              [nu x nv]     (optional)
%   trimMask          [nu x nv]     (optional logical)
%
% Expected WGS network struct fields:
%   X, Y, Z           [nRows x nCols]
%   name              (optional)
%   iSymX, iSymZ      (optional)

    methods (Static)
        %% ==============================================================
        % PanAir / LaWGS
        % ==============================================================
        function toWGS(networks, filename, configName)
            if nargin < 3 || isempty(configName)
                configName = 'generated by panair_geom_kernel';
            end
        
            if ~iscell(networks)
                tmp = networks;
                networks = cell(1, numel(tmp));
                for k = 1:numel(tmp)
                    networks{k} = tmp(k);
                end
            end
        
            fid = fopen(filename, 'w');
            if fid < 0
                error('Cannot open "%s" for writing.', filename);
            end
            c = onCleanup(@() fclose(fid));
        
            % Record 1: configuration ID
            fprintf(fid, '''%s''\n', configName);
        
            for k = 1:numel(networks)
                net = networks{k};
        
                % Basic checks
                assert(isfield(net,'X') && isfield(net,'Y') && isfield(net,'Z'), ...
                    'Network must contain X,Y,Z');
                assert(isequal(size(net.X), size(net.Y), size(net.Z)), ...
                    'X,Y,Z sizes must match');
        
                if ~isfield(net,'name') || isempty(net.name)
                    net.name = sprintf('Network_%d', k);
                end
                if ~isfield(net,'nobj') || isempty(net.nobj)
                    net.nobj = k;
                end
                if ~isfield(net,'isyml') || isempty(net.isyml)
                    net.isyml = 0;
                end
                if ~isfield(net,'rx'),     net.rx = 0; end
                if ~isfield(net,'ry'),     net.ry = 0; end
                if ~isfield(net,'rz'),     net.rz = 0; end
                if ~isfield(net,'tx'),     net.tx = 0; end
                if ~isfield(net,'ty'),     net.ty = 0; end
                if ~isfield(net,'tz'),     net.tz = 0; end
                if ~isfield(net,'xscale'), net.xscale = 1; end
                if ~isfield(net,'yscale'), net.yscale = 1; end
                if ~isfield(net,'zscale'), net.zscale = 1; end
                if ~isfield(net,'isymg') || isempty(net.isymg)
                    net.isymg = 0;
                end
        
                nline = size(net.X,1);   % contour lines
                npnt  = size(net.X,2);   % points per contour
        
                % Record 2: object ID
                fprintf(fid, '''%s''\n', net.name);
        
                % Record 3: object metadata
                fprintf(fid, '%d %d %d %d  %g %g %g  %g %g %g  %g %g %g  %d\n', ...
                    net.nobj, nline, npnt, net.isyml, ...
                    net.rx, net.ry, net.rz, ...
                    net.tx, net.ty, net.tz, ...
                    net.xscale, net.yscale, net.zscale, ...
                    net.isymg);
        
                % Record 4: one contour line per record block, written as x y z triples
                for i = 1:nline
                    for j = 1:npnt
                        fprintf(fid, '%.7e %.7e %.7e\n', ...
                            net.X(i,j), net.Y(i,j), net.Z(i,j));
                    end
                end
            end
        end

        %% ==============================================================
        % VTK legacy ASCII
        % ==============================================================
        function toVTK(mesh_or_networks, filename, varargin)
            pa = inputParser;
            addParameter(pa, 'IncludeNormals', true);
            addParameter(pa, 'BinaryMode', false); % accepted, ASCII only
            parse(pa, varargin{:});
            opts = pa.Results;

            if opts.BinaryMode
                warning('MeshWriter.toVTK: BinaryMode is not implemented; writing ASCII VTK.');
            end

            if ~iscell(mesh_or_networks)
                meshes = {mesh_or_networks};
            else
                meshes = mesh_or_networks;
            end

            all_pts = zeros(0, 3);
            all_quads = zeros(0, 4);
            all_nrms = zeros(0, 3);
            want_normals = opts.IncludeNormals;
            have_normals = true;

            offset = 0;

            for k = 1:numel(meshes)
                m = meshes{k};
                geom.MeshWriter.validateStructuredMesh(m, 'toVTK');

                [pts, quads, nrms, this_has_normals] = ...
                    geom.MeshWriter.meshToValidQuadSoup(m, offset);

                all_pts = [all_pts; pts]; %#ok<AGROW>
                all_quads = [all_quads; quads]; %#ok<AGROW>

                if want_normals && this_has_normals
                    all_nrms = [all_nrms; nrms]; %#ok<AGROW>
                else
                    have_normals = false;
                end

                offset = size(all_pts,1);
            end

            n_pts = size(all_pts,1);
            n_cells = size(all_quads,1);

            fid = fopen(filename, 'w');
            if fid < 0
                error('MeshWriter.toVTK: cannot open "%s" for writing.', filename);
            end
            c = onCleanup(@() fclose(fid));

            fprintf(fid, '# vtk DataFile Version 3.0\n');
            fprintf(fid, 'Aircraft Geometry Kernel surface mesh\n');
            fprintf(fid, 'ASCII\n');
            fprintf(fid, 'DATASET UNSTRUCTURED_GRID\n\n');

            fprintf(fid, 'POINTS %d float\n', n_pts);
            fprintf(fid, '%f %f %f\n', all_pts.');
            fprintf(fid, '\n');

            fprintf(fid, 'CELLS %d %d\n', n_cells, n_cells * 5);
            for q = 1:n_cells
                fprintf(fid, '4 %d %d %d %d\n', all_quads(q,:));
            end
            fprintf(fid, '\n');

            fprintf(fid, 'CELL_TYPES %d\n', n_cells);
            for q = 1:n_cells
                fprintf(fid, '9\n'); % VTK_QUAD
            end
            fprintf(fid, '\n');

            if want_normals && have_normals && ~isempty(all_nrms)
                fprintf(fid, 'POINT_DATA %d\n', n_pts);
                fprintf(fid, 'NORMALS SurfaceNormals float\n');
                fprintf(fid, '%f %f %f\n', all_nrms.');
            end

            fprintf('MeshWriter: wrote %d pts, %d quads to "%s"\n', n_pts, n_cells, filename);
        end

        %% ==============================================================
        % STL
        % ==============================================================
        function toSTL(mesh_or_networks, filename, varargin)
            pa = inputParser;
            addParameter(pa, 'AreaTolerance', 1e-12);
            parse(pa, varargin{:});
            opts = pa.Results;

            if ~iscell(mesh_or_networks)
                meshes = {mesh_or_networks};
            else
                meshes = mesh_or_networks;
            end

            fid = fopen(filename, 'w');
            if fid < 0
                error('MeshWriter.toSTL: cannot open "%s" for writing.', filename);
            end
            c = onCleanup(@() fclose(fid));

            solid_name = 'AircraftGeom';
            fprintf(fid, 'solid %s\n', solid_name);

            n_tris = 0;

            for k = 1:numel(meshes)
                m = meshes{k};
                geom.MeshWriter.validateStructuredMesh(m, 'toSTL');

                for i = 1:m.nu-1
                    for j = 1:m.nv-1
                        id1 = i     + (j-1) * m.nu;
                        id2 = i + 1 + (j-1) * m.nu;
                        id3 = i + 1 +  j    * m.nu;
                        id4 = i     +  j    * m.nu;

                        V = zeros(4,3);
                        V(1,:) = [m.X(i,j),     m.Y(i,j),     m.Z(i,j)];
                        V(2,:) = [m.X(i+1,j),   m.Y(i+1,j),   m.Z(i+1,j)];
                        V(3,:) = [m.X(i+1,j+1), m.Y(i+1,j+1), m.Z(i+1,j+1)];
                        V(4,:) = [m.X(i,j+1),   m.Y(i,j+1),   m.Z(i,j+1)];

                        if any(~isfinite(V(:)))
                            continue;
                        end

                        ids = [id1 id2 id3 id4];
                        ids = geom.MeshWriter.orientCellWithNormals(m, ids);
                        V = V([find([id1 id2 id3 id4] == ids(1),1), ...
                               find([id1 id2 id3 id4] == ids(2),1), ...
                               find([id1 id2 id3 id4] == ids(3),1), ...
                               find([id1 id2 id3 id4] == ids(4),1)], :);

                        [n1, a1] = geom.MeshWriter.triNormal(V(1,:), V(2,:), V(3,:));
                        if a1 > opts.AreaTolerance
                            fprintf(fid, ' facet normal %f %f %f\n', n1);
                            fprintf(fid, '  outer loop\n');
                            fprintf(fid, '   vertex %f %f %f\n', V(1,:));
                            fprintf(fid, '   vertex %f %f %f\n', V(2,:));
                            fprintf(fid, '   vertex %f %f %f\n', V(3,:));
                            fprintf(fid, '  endloop\n');
                            fprintf(fid, ' endfacet\n');
                            n_tris = n_tris + 1;
                        end

                        [n2, a2] = geom.MeshWriter.triNormal(V(1,:), V(3,:), V(4,:));
                        if a2 > opts.AreaTolerance
                            fprintf(fid, ' facet normal %f %f %f\n', n2);
                            fprintf(fid, '  outer loop\n');
                            fprintf(fid, '   vertex %f %f %f\n', V(1,:));
                            fprintf(fid, '   vertex %f %f %f\n', V(3,:));
                            fprintf(fid, '   vertex %f %f %f\n', V(4,:));
                            fprintf(fid, '  endloop\n');
                            fprintf(fid, ' endfacet\n');
                            n_tris = n_tris + 1;
                        end
                    end
                end
            end

            fprintf(fid, 'endsolid %s\n', solid_name);
            fprintf('MeshWriter: wrote %d triangles to "%s"\n', n_tris, filename);
        end

        %% ==============================================================
        % CSV
        % ==============================================================
        function toCSV(mesh, filename)
            geom.MeshWriter.validateStructuredMesh(mesh, 'toCSV');

            fid = fopen(filename, 'w');
            if fid < 0
                error('MeshWriter.toCSV: cannot open "%s".', filename);
            end
            c = onCleanup(@() fclose(fid));

            has_normals = isfield(mesh, 'normals') && ~isempty(mesh.normals);
            has_params  = isfield(mesh, 'u') && isfield(mesh, 'v');

            if has_normals && has_params
                fprintf(fid, 'x,y,z,nx,ny,nz,u,v\n');
            elseif has_normals
                fprintf(fid, 'x,y,z,nx,ny,nz\n');
            else
                fprintf(fid, 'x,y,z\n');
            end

            n_written = 0;
            for i = 1:mesh.nu
                for j = 1:mesh.nv
                    x = mesh.X(i,j);
                    y = mesh.Y(i,j);
                    z = mesh.Z(i,j);

                    if ~isfinite(x) || ~isfinite(y) || ~isfinite(z)
                        continue;
                    end

                    if has_normals && has_params
                        nx = mesh.normals(i,j,1);
                        ny = mesh.normals(i,j,2);
                        nz = mesh.normals(i,j,3);
                        fprintf(fid, '%.8f,%.8f,%.8f,%.6f,%.6f,%.6f,%.6f,%.6f\n', ...
                            x, y, z, nx, ny, nz, mesh.u(i,j), mesh.v(i,j));
                    elseif has_normals
                        nx = mesh.normals(i,j,1);
                        ny = mesh.normals(i,j,2);
                        nz = mesh.normals(i,j,3);
                        fprintf(fid, '%.8f,%.8f,%.8f,%.6f,%.6f,%.6f\n', ...
                            x, y, z, nx, ny, nz);
                    else
                        fprintf(fid, '%.8f,%.8f,%.8f\n', x, y, z);
                    end

                    n_written = n_written + 1;
                end
            end

            fprintf('MeshWriter: wrote %d CSV nodes to "%s"\n', n_written, filename);
        end

        %% ==============================================================
        % Helper: build WGS network struct from isoMesh output
        % ==============================================================
        function net = meshToNetwork(mesh, name, iSymX, iSymZ)
            if nargin < 2, name = 'Network'; end
            if nargin < 3, iSymX = 0; end
            if nargin < 4, iSymZ = 0; end

            geom.MeshWriter.validateStructuredMesh(mesh, 'meshToNetwork');

            net.X = mesh.X;
            net.Y = mesh.Y;
            net.Z = mesh.Z;
            net.nu = mesh.nu;
            net.nv = mesh.nv;
            net.name = name;
            net.iSymX = iSymX;
            net.iSymZ = iSymZ;
        end

        function checkNormals(mesh)
            if ~isfield(mesh, 'normals') || isempty(mesh.normals)
                error('MeshWriter.checkNormals: mesh has no normals field.');
            end

            nrm = reshape(mesh.normals, [], 3);
            keep = all(isfinite(nrm), 2);
            nrm = nrm(keep, :);

            if isempty(nrm)
                fprintf('Normal direction statistics: no finite normals available.\n');
                return;
            end

            fprintf('Normal direction statistics:\n');
            fprintf(' Mean normal: [%.3f %.3f %.3f]\n', mean(nrm,1));
            fprintf(' Z-component: min=%.3f max=%.3f\n', min(nrm(:,3)), max(nrm(:,3)));

            z_pos_frac = sum(nrm(:,3) > 0) / size(nrm,1);
            fprintf(' Fraction pointing +Z: %.1f%%\n', 100 * z_pos_frac);

            if z_pos_frac < 0.5
                fprintf(' WARNING: normals may need flipping.\n');
            end
        end
    end

    methods (Static, Access = private)
        function validateStructuredMesh(mesh, callerName)
            req = {'X','Y','Z','nu','nv'};
            for k = 1:numel(req)
                if ~isfield(mesh, req{k})
                    error('MeshWriter.%s: mesh missing required field "%s".', callerName, req{k});
                end
            end

            szX = size(mesh.X);
            szY = size(mesh.Y);
            szZ = size(mesh.Z);

            if ~isequal(szX, szY, szZ)
                error('MeshWriter.%s: X, Y, Z must have matching sizes.', callerName);
            end

            if numel(szX) ~= 2
                error('MeshWriter.%s: X, Y, Z must be 2D arrays.', callerName);
            end

            if szX(1) ~= mesh.nu || szX(2) ~= mesh.nv
                error('MeshWriter.%s: mesh.nu/nv do not match X/Y/Z size.', callerName);
            end
        end

        function validateNetwork(net, callerName)
            req = {'X','Y','Z'};
            for k = 1:numel(req)
                if ~isfield(net, req{k})
                    error('MeshWriter.%s: network missing required field "%s".', callerName, req{k});
                end
            end

            szX = size(net.X);
            szY = size(net.Y);
            szZ = size(net.Z);

            if ~isequal(szX, szY, szZ)
                error('MeshWriter.%s: network X, Y, Z must have matching sizes.', callerName);
            end

            if numel(szX) ~= 2
                error('MeshWriter.%s: network X/Y/Z must be 2D arrays.', callerName);
            end
        end

        function [pts, quads, nrms, has_normals] = meshToValidQuadSoup(mesh, offset0)
            % pts = [X(:), Y(:), Z(:)] uses MATLAB column-major ordering.
            % For an [nu x nv] array:
            %   idx(i,j) = i + (j-1)*nu

            pts = [mesh.X(:), mesh.Y(:), mesh.Z(:)];

            if isfield(mesh, 'normals') && ~isempty(mesh.normals)
                nrms = reshape(mesh.normals, [], 3);
                has_normals = size(nrms,1) == size(pts,1);
            else
                nrms = zeros(0,3);
                has_normals = false;
            end

            quads = zeros(0,4);
            nu = mesh.nu;

            for i = 1:mesh.nu-1
                for j = 1:mesh.nv-1
                    id1 = i     + (j-1) * nu;
                    id2 = i + 1 + (j-1) * nu;
                    id3 = i + 1 +  j    * nu;
                    id4 = i     +  j    * nu;

                    V = pts([id1 id2 id3 id4], :);
                    if any(~isfinite(V(:)))
                        continue;
                    end

                    ids = [id1 id2 id3 id4];
                    ids = geom.MeshWriter.orientCellWithNormals(mesh, ids);

                    quads(end+1,:) = offset0 + (ids - 1); %#ok<AGROW>
                end
            end
        end

        function ids = orientCellWithNormals(mesh, ids)
            if ~isfield(mesh, 'normals') || isempty(mesh.normals)
                return;
            end

            pts = [mesh.X(:), mesh.Y(:), mesh.Z(:)];
            nrms = reshape(mesh.normals, [], 3);

            V = pts(ids, :);
            N = nrms(ids, :);
            keep = all(isfinite(N), 2);

            if ~any(keep)
                return;
            end

            navg = mean(N(keep, :), 1);
            nrm = norm(navg);
            if nrm < eps
                return;
            end
            navg = navg / nrm;

            ncell = cross(V(2,:) - V(1,:), V(3,:) - V(1,:));
            nrm2 = norm(ncell);
            if nrm2 < eps
                return;
            end
            ncell = ncell / nrm2;

            if dot(ncell, navg) < 0
                ids = [ids(1), ids(4), ids(3), ids(2)];
            end
        end

        function [n, area2] = triNormal(V1, V2, V3)
            e1 = V2 - V1;
            e2 = V3 - V1;
            n = cross(e1, e2);
            area2 = norm(n);
            if area2 > eps
                n = n / area2;
            else
                n = [0 0 0];
            end
        end
    end
end