classdef MeshWriter
% MESHWRITER Export structured surface meshes to various formats.
%
% Supported exports:
%   - LaWGS / PanAir WGS
%   - VTK legacy ASCII unstructured grid
%   - ASCII STL
%   - CSV node dump
%
% Expected mesh struct fields from geom.NURBSSurface.isoMesh():
%   X, Y, Z           [nu x nv]
%   nu, nv
%   normals           [nu x nv x 3] (optional)
%   u, v              [nu x nv]     (optional)
%   trimMask          [nu x nv]     (optional logical)
%
% Expected WGS network struct fields:
%   X, Y, Z           [nRows x nCols]
%   name              (optional)
%   iSymX, iSymZ      (optional)

    methods (Static)
        %% ==============================================================
        % PanAir / LaWGS
        % ==============================================================
        function toWGS(networks, filename, configName)
            if nargin < 3 || isempty(configName)
                configName = 'generated by panair_geom_kernel';
            end
        
            if ~iscell(networks)
                tmp = networks;
                networks = cell(1, numel(tmp));
                for k = 1:numel(tmp)
                    networks{k} = tmp(k);
                end
            end
        
            fid = fopen(filename, 'w');
            if fid < 0
                error('Cannot open "%s" for writing.', filename);
            end
            c = onCleanup(@() fclose(fid));
        
            % Record 1: configuration ID
            fprintf(fid, '''%s''\n', configName);
        
            for k = 1:numel(networks)
                net = networks{k};
        
                geom.MeshWriter.validateNetwork(net, 'toWGS');
        
                if ~isfield(net,'name') || isempty(net.name)
                    net.name = sprintf('Network_%d', k);
                end
                if ~isfield(net,'nobj') || isempty(net.nobj)
                    net.nobj = k;
                end
                if ~isfield(net,'isyml') || isempty(net.isyml)
                    net.isyml = 0;
                end
                if ~isfield(net,'rx'),     net.rx = 0; end
                if ~isfield(net,'ry'),     net.ry = 0; end
                if ~isfield(net,'rz'),     net.rz = 0; end
                if ~isfield(net,'tx'),     net.tx = 0; end
                if ~isfield(net,'ty'),     net.ty = 0; end
                if ~isfield(net,'tz'),     net.tz = 0; end
                if ~isfield(net,'xscale'), net.xscale = 1; end
                if ~isfield(net,'yscale'), net.yscale = 1; end
                if ~isfield(net,'zscale'), net.zscale = 1; end
                if ~isfield(net,'isymg') || isempty(net.isymg)
                    net.isymg = 0;
                end
        
                nline = size(net.X,1);   % contour lines
                npnt  = size(net.X,2);   % points per contour
        
                % Record 2: object ID
                fprintf(fid, '''%s''\n', net.name);
        
                % Record 3: object metadata
                fprintf(fid, '%d %d %d %d  %g %g %g  %g %g %g  %g %g %g  %d\n', ...
                    net.nobj, nline, npnt, net.isyml, ...
                    net.rx, net.ry, net.rz, ...
                    net.tx, net.ty, net.tz, ...
                    net.xscale, net.yscale, net.zscale, ...
                    net.isymg);
        
                % Record 4: one contour line per record block, written as x y z triples
                for i = 1:nline
                    for j = 1:npnt
                        fprintf(fid, '%.7e %.7e %.7e\n', ...
                            net.X(i,j), net.Y(i,j), net.Z(i,j));
                    end
                end
            end
        end

        %% ==============================================================
        % VTK legacy ASCII
        % ==============================================================
        function toVTK(mesh_or_networks, filename, varargin)
            pa = inputParser;
            addParameter(pa, 'IncludeNormals', true);
            addParameter(pa, 'BinaryMode', false); % accepted, ASCII only
            parse(pa, varargin{:});
            opts = pa.Results;

            if opts.BinaryMode
                warning('MeshWriter.toVTK: BinaryMode is not implemented; writing ASCII VTK.');
            end

            if ~iscell(mesh_or_networks)
                meshes = {mesh_or_networks};
            else
                meshes = mesh_or_networks;
            end

            all_pts = zeros(0, 3);
            all_quads = zeros(0, 4);
            all_nrms = zeros(0, 3);
            want_normals = opts.IncludeNormals;
            have_normals = true;

            offset = 0;

            for k = 1:numel(meshes)
                m = meshes{k};
                geom.MeshWriter.validateStructuredMesh(m, 'toVTK');

                [pts, quads, nrms, this_has_normals] = ...
                    geom.MeshWriter.meshToValidQuadSoup(m, offset);

                all_pts = [all_pts; pts]; %#ok<AGROW>
                all_quads = [all_quads; quads]; %#ok<AGROW>

                if want_normals && this_has_normals
                    all_nrms = [all_nrms; nrms]; %#ok<AGROW>
                else
                    have_normals = false;
                end

                offset = size(all_pts,1);
            end

            n_pts = size(all_pts,1);
            n_cells = size(all_quads,1);

            fid = fopen(filename, 'w');
            if fid < 0
                error('MeshWriter.toVTK: cannot open "%s" for writing.', filename);
            end
            c = onCleanup(@() fclose(fid));

            fprintf(fid, '# vtk DataFile Version 3.0\n');
            fprintf(fid, 'Aircraft Geometry Kernel surface mesh\n');
            fprintf(fid, 'ASCII\n');
            fprintf(fid, 'DATASET UNSTRUCTURED_GRID\n\n');

            fprintf(fid, 'POINTS %d float\n', n_pts);
            fprintf(fid, '%f %f %f\n', all_pts.');
            fprintf(fid, '\n');

            fprintf(fid, 'CELLS %d %d\n', n_cells, n_cells * 5);
            for q = 1:n_cells
                fprintf(fid, '4 %d %d %d %d\n', all_quads(q,:));
            end
            fprintf(fid, '\n');

            fprintf(fid, 'CELL_TYPES %d\n', n_cells);
            for q = 1:n_cells
                fprintf(fid, '9\n'); % VTK_QUAD
            end
            fprintf(fid, '\n');

            if want_normals && have_normals && ~isempty(all_nrms)
                fprintf(fid, 'POINT_DATA %d\n', n_pts);
                fprintf(fid, 'NORMALS SurfaceNormals float\n');
                fprintf(fid, '%f %f %f\n', all_nrms.');
            end

            fprintf('MeshWriter: wrote %d pts, %d quads to "%s"\n', n_pts, n_cells, filename);
        end

        %% ==============================================================
        % STL
        % ==============================================================
        function toSTL(mesh_or_networks, filename, varargin)
            pa = inputParser;
            addParameter(pa, 'AreaTolerance', 1e-12);
            parse(pa, varargin{:});
            opts = pa.Results;

            if ~iscell(mesh_or_networks)
                meshes = {mesh_or_networks};
            else
                meshes = mesh_or_networks;
            end

            fid = fopen(filename, 'w');
            if fid < 0
                error('MeshWriter.toSTL: cannot open "%s" for writing.', filename);
            end
            c = onCleanup(@() fclose(fid));

            solid_name = 'AircraftGeom';
            fprintf(fid, 'solid %s\n', solid_name);

            n_tris = 0;

            for k = 1:numel(meshes)
                m = meshes{k};
                geom.MeshWriter.validateStructuredMesh(m, 'toSTL');

                for i = 1:m.nu-1
                    for j = 1:m.nv-1
                        id1 = i     + (j-1) * m.nu;
                        id2 = i + 1 + (j-1) * m.nu;
                        id3 = i + 1 +  j    * m.nu;
                        id4 = i     +  j    * m.nu;

                        V = zeros(4,3);
                        V(1,:) = [m.X(i,j),     m.Y(i,j),     m.Z(i,j)];
                        V(2,:) = [m.X(i+1,j),   m.Y(i+1,j),   m.Z(i+1,j)];
                        V(3,:) = [m.X(i+1,j+1), m.Y(i+1,j+1), m.Z(i+1,j+1)];
                        V(4,:) = [m.X(i,j+1),   m.Y(i,j+1),   m.Z(i,j+1)];

                        if any(~isfinite(V(:)))
                            continue;
                        end

                        ids = [id1 id2 id3 id4];
                        ids = geom.MeshWriter.orientCellWithNormals(m, ids);
                        V = V([find([id1 id2 id3 id4] == ids(1),1), ...
                               find([id1 id2 id3 id4] == ids(2),1), ...
                               find([id1 id2 id3 id4] == ids(3),1), ...
                               find([id1 id2 id3 id4] == ids(4),1)], :);

                        [n1, a1] = geom.MeshWriter.triNormal(V(1,:), V(2,:), V(3,:));
                        if a1 > opts.AreaTolerance
                            fprintf(fid, ' facet normal %f %f %f\n', n1);
                            fprintf(fid, '  outer loop\n');
                            fprintf(fid, '   vertex %f %f %f\n', V(1,:));
                            fprintf(fid, '   vertex %f %f %f\n', V(2,:));
                            fprintf(fid, '   vertex %f %f %f\n', V(3,:));
                            fprintf(fid, '  endloop\n');
                            fprintf(fid, ' endfacet\n');
                            n_tris = n_tris + 1;
                        end

                        [n2, a2] = geom.MeshWriter.triNormal(V(1,:), V(3,:), V(4,:));
                        if a2 > opts.AreaTolerance
                            fprintf(fid, ' facet normal %f %f %f\n', n2);
                            fprintf(fid, '  outer loop\n');
                            fprintf(fid, '   vertex %f %f %f\n', V(1,:));
                            fprintf(fid, '   vertex %f %f %f\n', V(3,:));
                            fprintf(fid, '   vertex %f %f %f\n', V(4,:));
                            fprintf(fid, '  endloop\n');
                            fprintf(fid, ' endfacet\n');
                            n_tris = n_tris + 1;
                        end
                    end
                end
            end

            fprintf(fid, 'endsolid %s\n', solid_name);
            fprintf('MeshWriter: wrote %d triangles to "%s"\n', n_tris, filename);
        end

        %% ==============================================================
        % CSV
        % ==============================================================
        function toCSV(mesh, filename)
            geom.MeshWriter.validateStructuredMesh(mesh, 'toCSV');

            fid = fopen(filename, 'w');
            if fid < 0
                error('MeshWriter.toCSV: cannot open "%s".', filename);
            end
            c = onCleanup(@() fclose(fid));

            has_normals = isfield(mesh, 'normals') && ~isempty(mesh.normals);
            has_params  = isfield(mesh, 'u') && isfield(mesh, 'v');

            if has_normals && has_params
                fprintf(fid, 'x,y,z,nx,ny,nz,u,v\n');
            elseif has_normals
                fprintf(fid, 'x,y,z,nx,ny,nz\n');
            else
                fprintf(fid, 'x,y,z\n');
            end

            n_written = 0;
            for i = 1:mesh.nu
                for j = 1:mesh.nv
                    x = mesh.X(i,j);
                    y = mesh.Y(i,j);
                    z = mesh.Z(i,j);

                    if ~isfinite(x) || ~isfinite(y) || ~isfinite(z)
                        continue;
                    end

                    if has_normals && has_params
                        nx = mesh.normals(i,j,1);
                        ny = mesh.normals(i,j,2);
                        nz = mesh.normals(i,j,3);
                        fprintf(fid, '%.8f,%.8f,%.8f,%.6f,%.6f,%.6f,%.6f,%.6f\n', ...
                            x, y, z, nx, ny, nz, mesh.u(i,j), mesh.v(i,j));
                    elseif has_normals
                        nx = mesh.normals(i,j,1);
                        ny = mesh.normals(i,j,2);
                        nz = mesh.normals(i,j,3);
                        fprintf(fid, '%.8f,%.8f,%.8f,%.6f,%.6f,%.6f\n', ...
                            x, y, z, nx, ny, nz);
                    else
                        fprintf(fid, '%.8f,%.8f,%.8f\n', x, y, z);
                    end

                    n_written = n_written + 1;
                end
            end

            fprintf('MeshWriter: wrote %d CSV nodes to "%s"\n', n_written, filename);
        end

        %% ==============================================================
        % Helper: build WGS network struct from isoMesh output
        % ==============================================================
        function net = meshToNetwork(mesh, name, iSymX, iSymZ)
            if nargin < 2, name = 'Network'; end
            if nargin < 3, iSymX = 0; end
            if nargin < 4, iSymZ = 0; end

            geom.MeshWriter.validateStructuredMesh(mesh, 'meshToNetwork');

            net.X = mesh.X;
            net.Y = mesh.Y;
            net.Z = mesh.Z;
            net.nu = mesh.nu;
            net.nv = mesh.nv;
            net.name = name;
            net.iSymX = iSymX;
            net.iSymZ = iSymZ;
            if contains(upper(name), 'WAKE')
                net.boun = 18;
            else
                net.boun = 1;
            end
        end

        function report = auditWGSNetworks(networks, varargin)
            pa = inputParser;
            addParameter(pa, 'Tolerance', 1e-10);
            addParameter(pa, 'Verbose', false);
            parse(pa, varargin{:});
            opts = pa.Results;

            if ~iscell(networks)
                tmp = networks;
                networks = cell(1, numel(tmp));
                for k = 1:numel(tmp)
                    networks{k} = tmp(k);
                end
            end

            nNet = numel(networks);
            edgeTable = struct('netIndex', {}, 'netName', {}, 'edgeName', {}, ...
                'npts', {}, 'collapsed', {}, 'length', {}, 'P', {});
            idx = 1;
            edgeNames = {'i1','iN','j1','jN'};

            for k = 1:nNet
                net = networks{k};
                geom.MeshWriter.validateNetwork(net, 'auditWGSNetworks');
                netName = geom.MeshWriter.getNetworkName(net, k);
                for e = 1:numel(edgeNames)
                    P = geom.MeshWriter.getNetworkEdge(net, edgeNames{e});
                    edgeTable(idx).netIndex = k;
                    edgeTable(idx).netName = netName;
                    edgeTable(idx).edgeName = edgeNames{e};
                    edgeTable(idx).npts = size(P,1);
                    edgeTable(idx).collapsed = geom.MeshWriter.isCollapsedEdge(P, opts.Tolerance);
                    edgeTable(idx).length = geom.MeshWriter.edgeArcLength(P);
                    edgeTable(idx).P = P;
                    idx = idx + 1;
                end
            end

            matches = struct('a', {}, 'b', {}, 'sameError', {}, 'revError', {}, ...
                'bestError', {}, 'orientation', {}, 'withinTol', {});
            idx = 1;
            for a = 1:numel(edgeTable)-1
                for b = a+1:numel(edgeTable)
                    cmp = geom.MeshWriter.compareEdges(edgeTable(a).P, edgeTable(b).P);
                    matches(idx).a = a;
                    matches(idx).b = b;
                    matches(idx).sameError = cmp.sameError;
                    matches(idx).revError = cmp.revError;
                    matches(idx).bestError = cmp.bestError;
                    matches(idx).orientation = cmp.orientation;
                    matches(idx).withinTol = cmp.withinTol && (cmp.bestError <= opts.Tolerance);
                    idx = idx + 1;
                end
            end

            report = struct();
            report.tolerance = opts.Tolerance;
            report.edges = edgeTable;
            report.matches = matches;

            if opts.Verbose
                fprintf('MeshWriter edge audit (tol = %.3e)\n', opts.Tolerance);
                for a = 1:numel(edgeTable)
                    ed = edgeTable(a);
                    fprintf('  %-12s %-2s  n=%3d  len=%.6e', ed.netName, ed.edgeName, ed.npts, ed.length);
                    if ed.collapsed
                        fprintf('  [collapsed]');
                    end
                    fprintf('\n');
                end
                fprintf('  Candidate matches within tolerance:\n');
                nShown = 0;
                for m = 1:numel(matches)
                    if matches(m).withinTol
                        ea = edgeTable(matches(m).a);
                        eb = edgeTable(matches(m).b);
                        fprintf('    %-12s %-2s <-> %-12s %-2s  err=%.3e  mode=%s\n', ...
                            ea.netName, ea.edgeName, eb.netName, eb.edgeName, ...
                            matches(m).bestError, matches(m).orientation);
                        nShown = nShown + 1;
                    end
                end
                if nShown == 0
                    fprintf('    none\n');
                end
            end
        end


        function assertExpectedMatches(networks, expectedPairs, varargin)
            pa = inputParser;
            addParameter(pa, 'Tolerance', 1e-10);
            addParameter(pa, 'RequireReversed', false);
            parse(pa, varargin{:});
            opts = pa.Results;

            if ~iscell(networks)
                tmp = networks;
                networks = cell(1, numel(tmp));
                for k = 1:numel(tmp)
                    networks{k} = tmp(k);
                end
            end

            if isempty(expectedPairs)
                return;
            end

            if iscell(expectedPairs)
                pairs = expectedPairs;
            else
                error('expectedPairs must be a cell array.');
            end

            for r = 1:size(pairs,1)
                nameA = pairs{r,1};
                edgeA = pairs{r,2};
                nameB = pairs{r,3};
                edgeB = pairs{r,4};

                idxA = geom.MeshWriter.findNetworkByName(networks, nameA);
                idxB = geom.MeshWriter.findNetworkByName(networks, nameB);
                PA = geom.MeshWriter.getNetworkEdge(networks{idxA}, edgeA);
                PB = geom.MeshWriter.getNetworkEdge(networks{idxB}, edgeB);
                cmp = geom.MeshWriter.compareEdges(PA, PB);
                if ~cmp.withinTol || cmp.bestError > opts.Tolerance
                    error(['MeshWriter.assertExpectedMatches: expected edge match failed: ' ...
                        '%s %s <-> %s %s (best err = %.3e, mode = %s).'], ...
                        char(nameA), char(edgeA), char(nameB), char(edgeB), ...
                        cmp.bestError, cmp.orientation);
                end
                if opts.RequireReversed && ~strcmpi(cmp.orientation, 'reversed')
                    error(['MeshWriter.assertExpectedMatches: expected reversed orientation failed: ' ...
                        '%s %s <-> %s %s (err = %.3e, mode = %s).'], ...
                        char(nameA), char(edgeA), char(nameB), char(edgeB), ...
                        cmp.bestError, cmp.orientation);
                end
                fprintf(' verified edge match: %s %s <-> %s %s  err=%.3e  mode=%s\n', ...
                    char(nameA), char(edgeA), char(nameB), char(edgeB), ...
                    cmp.bestError, cmp.orientation);
            end
        end

        function assertTopologyRules(networks, rules, varargin)
            pa = inputParser;
            addParameter(pa, 'Tolerance', 1e-10);
            addParameter(pa, 'Verbose', false);
            parse(pa, varargin{:});
            opts = pa.Results;

            if ~iscell(networks)
                tmp = networks;
                networks = cell(1, numel(tmp));
                for k = 1:numel(tmp)
                    networks{k} = tmp(k);
                end
            end
            if isempty(rules)
                return;
            end
            if ~iscell(rules)
                error('MeshWriter.assertTopologyRules: rules must be a cell array.');
            end

            report = geom.MeshWriter.auditWGSNetworks(networks, 'Tolerance', opts.Tolerance, 'Verbose', false);
            edges = report.edges;
            matches = report.matches;

            % Annotate edge degree using within-tolerance matches.
            degree = zeros(1, numel(edges));
            partnerList = cell(1, numel(edges));
            for m = 1:numel(matches)
                if matches(m).withinTol && matches(m).bestError <= opts.Tolerance
                    a = matches(m).a;
                    b = matches(m).b;
                    degree(a) = degree(a) + 1;
                    degree(b) = degree(b) + 1;
                    partnerList{a}(end+1) = b; %#ok<AGROW>
                    partnerList{b}(end+1) = a; %#ok<AGROW>
                end
            end
            for e = 1:numel(edges)
                edges(e).degree = degree(e);
                edges(e).partners = partnerList{e};
            end

            % Map rules to edge indices.
            ruleInfo = struct('netName', {}, 'edgeName', {}, 'kind', {}, 'group', {}, ...
                'partnerNet', {}, 'partnerEdge', {}, 'edgeIndex', {});
            for r = 1:size(rules,1)
                ruleInfo(r).netName = char(rules{r,1});
                ruleInfo(r).edgeName = char(rules{r,2});
                ruleInfo(r).kind = lower(strtrim(char(rules{r,3})));
                ruleInfo(r).group = char(rules{r,4});
                ruleInfo(r).partnerNet = char(rules{r,5});
                ruleInfo(r).partnerEdge = char(rules{r,6});
                ruleInfo(r).edgeIndex = geom.MeshWriter.findEdgeRecordIndex(edges, ruleInfo(r).netName, ruleInfo(r).edgeName);
            end

            % Regular one-to-one abutments.
            for r = 1:numel(ruleInfo)
                rr = ruleInfo(r);
                if strcmp(rr.kind, 'regular')
                    idxA = rr.edgeIndex;
                    idxB = geom.MeshWriter.findEdgeRecordIndex(edges, rr.partnerNet, rr.partnerEdge);
                    cmp = geom.MeshWriter.compareEdges(edges(idxA).P, edges(idxB).P);
                    if ~(cmp.withinTol && cmp.bestError <= opts.Tolerance)
                        error('MeshWriter.assertTopologyRules: regular match failed: %s %s <-> %s %s (err=%.3e, mode=%s).', ...
                            rr.netName, rr.edgeName, rr.partnerNet, rr.partnerEdge, cmp.bestError, cmp.orientation);
                    end
                    if ~strcmpi(cmp.orientation, 'reversed')
                        error('MeshWriter.assertTopologyRules: regular match must be reversed: %s %s <-> %s %s (err=%.3e, mode=%s).', ...
                            rr.netName, rr.edgeName, rr.partnerNet, rr.partnerEdge, cmp.bestError, cmp.orientation);
                    end
                    if edges(idxA).degree ~= 1
                        error('MeshWriter.assertTopologyRules: regular edge %s %s has degree %d; expected exactly 1.', ...
                            rr.netName, rr.edgeName, edges(idxA).degree);
                    end
                    if edges(idxB).degree ~= 1
                        error('MeshWriter.assertTopologyRules: regular edge %s %s has degree %d; expected exactly 1.', ...
                            rr.partnerNet, rr.partnerEdge, edges(idxB).degree);
                    end
                    if opts.Verbose
                        fprintf(' topology ok (regular): %s %s <-> %s %s  err=%.3e\n', ...
                            rr.netName, rr.edgeName, rr.partnerNet, rr.partnerEdge, cmp.bestError);
                    end
                end
            end

            % Sharp trailing-edge manifolds.
            groupCells = {ruleInfo(strcmp({ruleInfo.kind}, 'sharp_te')).group};
            groups = unique(groupCells);
            for g = 1:numel(groups)
                grp = char(groups{g});
                if isempty(strtrim(grp))
                    continue;
                end
                members = find(strcmp({ruleInfo.kind}, 'sharp_te') & strcmp({ruleInfo.group}, grp));
                edgeIdx = [ruleInfo(members).edgeIndex];
                for a = 1:numel(edgeIdx)-1
                    for b = a+1:numel(edgeIdx)
                        cmp = geom.MeshWriter.compareEdges(edges(edgeIdx(a)).P, edges(edgeIdx(b)).P);
                        if ~(cmp.withinTol && cmp.bestError <= opts.Tolerance)
                            ea = edges(edgeIdx(a));
                            eb = edges(edgeIdx(b));
                            error('MeshWriter.assertTopologyRules: sharp_te group %s mismatch: %s %s <-> %s %s (err=%.3e, mode=%s).', ...
                                grp, ea.netName, ea.edgeName, eb.netName, eb.edgeName, cmp.bestError, cmp.orientation);
                        end
                    end
                end
                allowed = sort(edgeIdx);
                for k = 1:numel(edgeIdx)
                    idxA = edgeIdx(k);
                    actual = sort(edges(idxA).partners);
                    if ~isequal(actual, setdiff(allowed, idxA))
                        ea = edges(idxA);
                        error('MeshWriter.assertTopologyRules: sharp_te edge %s %s has unexpected partner set.', ...
                            ea.netName, ea.edgeName);
                    end
                    if opts.Verbose
                        ea = edges(idxA);
                        fprintf(' topology ok (sharp_te): %s %s  degree=%d\n', ea.netName, ea.edgeName, edges(idxA).degree);
                    end
                end
            end

            % Allowed collapsed edges: must be collapsed and unmatched externally.
            for r = 1:numel(ruleInfo)
                rr = ruleInfo(r);
                if strcmp(rr.kind, 'collapsed')
                    idxA = rr.edgeIndex;
                    ea = edges(idxA);
                    if ~ea.collapsed
                        error('MeshWriter.assertTopologyRules: edge %s %s was expected to be collapsed but is not.', ...
                            rr.netName, rr.edgeName);
                    end
                    if ea.degree ~= 0
                        error('MeshWriter.assertTopologyRules: collapsed edge %s %s has %d matches; expected 0.', ...
                            rr.netName, rr.edgeName, ea.degree);
                    end
                    if opts.Verbose
                        fprintf(' topology ok (collapsed): %s %s\n', rr.netName, rr.edgeName);
                    end
                end
            end
        end

        function P = getNetworkEdge(net, edgeName)
            geom.MeshWriter.validateNetwork(net, 'getNetworkEdge');
            switch lower(strtrim(edgeName))
                case {'i1','imin','row1','edge4'}
                    P = [net.X(1,:).',   net.Y(1,:).',   net.Z(1,:).'];
                case {'in','imax','rowend','edge2'}
                    P = [net.X(end,:).', net.Y(end,:).', net.Z(end,:).'];
                case {'j1','jmin','col1','edge1'}
                    P = [net.X(:,1),     net.Y(:,1),     net.Z(:,1)];
                case {'jn','jmax','colend','edge3'}
                    P = [net.X(:,end),   net.Y(:,end),   net.Z(:,end)];
                otherwise
                    error('MeshWriter.getNetworkEdge: unknown edge name "%s".', edgeName);
            end
        end

        function cmp = compareEdges(P, Q)
            cmp = struct('sameError', inf, 'revError', inf, 'bestError', inf, ...
                'orientation', 'none', 'withinTol', false);
            if size(P,2) ~= 3 || size(Q,2) ~= 3
                return;
            end
            if size(P,1) ~= size(Q,1)
                return;
            end
            dSame = vecnorm(P - Q, 2, 2);
            dRev  = vecnorm(P - flipud(Q), 2, 2);
            cmp.sameError = max(dSame);
            cmp.revError = max(dRev);
            if cmp.sameError <= cmp.revError
                cmp.bestError = cmp.sameError;
                cmp.orientation = 'same';
            else
                cmp.bestError = cmp.revError;
                cmp.orientation = 'reversed';
            end
            cmp.withinTol = isfinite(cmp.bestError);
        end

        function checkNormals(mesh)
            if ~isfield(mesh, 'normals') || isempty(mesh.normals)
                error('MeshWriter.checkNormals: mesh has no normals field.');
            end

            nrm = reshape(mesh.normals, [], 3);
            keep = all(isfinite(nrm), 2);
            nrm = nrm(keep, :);

            if isempty(nrm)
                fprintf('Normal direction statistics: no finite normals available.\n');
                return;
            end

            fprintf('Normal direction statistics:\n');
            fprintf(' Mean normal: [%.3f %.3f %.3f]\n', mean(nrm,1));
            fprintf(' Z-component: min=%.3f max=%.3f\n', min(nrm(:,3)), max(nrm(:,3)));

            z_pos_frac = sum(nrm(:,3) > 0) / size(nrm,1);
            fprintf(' Fraction pointing +Z: %.1f%%\n', 100 * z_pos_frac);

            if z_pos_frac < 0.5
                fprintf(' WARNING: normals may need flipping.\n');
            end
        end

        function n = averageNetworkNormal(net)
            X = net.X; Y = net.Y; Z = net.Z;
        
            acc = [0 0 0];
            cnt = 0;
        
            for i = 1:(size(X,1)-1)
                for j = 1:(size(X,2)-1)
        
                    p00 = [X(i,j),   Y(i,j),   Z(i,j)];
                    p10 = [X(i+1,j), Y(i+1,j), Z(i+1,j)];
                    p01 = [X(i,j+1), Y(i,j+1), Z(i,j+1)];
        
                    v1 = p10 - p00;
                    v2 = p01 - p00;
        
                    nloc = cross(v1, v2);
                    mag = norm(nloc);
        
                    if mag > 0
                        acc = acc + nloc / mag;
                        cnt = cnt + 1;
                    end
                end
            end
        
            if cnt > 0
                n = acc / cnt;
                n = n / norm(n);
            else
                n = [0 0 0];
            end
        end

        function mesh = flipMesh(mesh, dir)
            switch lower(dir)
                case 'u'
                    mesh.X = flipud(mesh.X);
                    mesh.Y = flipud(mesh.Y);
                    mesh.Z = flipud(mesh.Z);
                case 'v'
                    mesh.X = fliplr(mesh.X);
                    mesh.Y = fliplr(mesh.Y);
                    mesh.Z = fliplr(mesh.Z);
                otherwise
                    error('flipMesh: dir must be u or v');
            end
        end
        function mesh = enforceNormalDirection(mesh, expected)
            n = geom.MeshWriter.averageNetworkNormal(mesh);
        
            switch lower(expected)
                case 'up'
                    if n(3) < 0
                        mesh = geom.MeshWriter.flipMesh(mesh, 'u');
                    end
        
                case 'down'
                    if n(3) > 0
                        mesh = geom.MeshWriter.flipMesh(mesh, 'u');
                    end
        
                case 'outboard'
                    if n(2) < 0
                        mesh = geom.MeshWriter.flipMesh(mesh, 'u');
                    end
        
                otherwise
                    error('Unknown expected normal direction');
            end
        end

    end

    methods (Static, Access = private)
        function validateStructuredMesh(mesh, callerName)
            req = {'X','Y','Z','nu','nv'};
            for k = 1:numel(req)
                if ~isfield(mesh, req{k})
                    error('MeshWriter.%s: mesh missing required field "%s".', callerName, req{k});
                end
            end

            szX = size(mesh.X);
            szY = size(mesh.Y);
            szZ = size(mesh.Z);

            if ~isequal(szX, szY, szZ)
                error('MeshWriter.%s: X, Y, Z must have matching sizes.', callerName);
            end

            if numel(szX) ~= 2
                error('MeshWriter.%s: X, Y, Z must be 2D arrays.', callerName);
            end

            if szX(1) ~= mesh.nu || szX(2) ~= mesh.nv
                error('MeshWriter.%s: mesh.nu/nv do not match X/Y/Z size.', callerName);
            end
        end

        function validateNetwork(net, callerName)
            req = {'X','Y','Z'};
            for k = 1:numel(req)
                if ~isfield(net, req{k})
                    error('MeshWriter.%s: network missing required field "%s".', callerName, req{k});
                end
            end

            szX = size(net.X);
            szY = size(net.Y);
            szZ = size(net.Z);

            if ~isequal(szX, szY, szZ)
                error('MeshWriter.%s: network X, Y, Z must have matching sizes.', callerName);
            end

            if numel(szX) ~= 2
                error('MeshWriter.%s: network X/Y/Z must be 2D arrays.', callerName);
            end
        end

        function [pts, quads, nrms, has_normals] = meshToValidQuadSoup(mesh, offset0)
            % pts = [X(:), Y(:), Z(:)] uses MATLAB column-major ordering.
            % For an [nu x nv] array:
            %   idx(i,j) = i + (j-1)*nu

            pts = [mesh.X(:), mesh.Y(:), mesh.Z(:)];

            if isfield(mesh, 'normals') && ~isempty(mesh.normals)
                nrms = reshape(mesh.normals, [], 3);
                has_normals = size(nrms,1) == size(pts,1);
            else
                nrms = zeros(0,3);
                has_normals = false;
            end

            quads = zeros(0,4);
            nu = mesh.nu;

            for i = 1:mesh.nu-1
                for j = 1:mesh.nv-1
                    id1 = i     + (j-1) * nu;
                    id2 = i + 1 + (j-1) * nu;
                    id3 = i + 1 +  j    * nu;
                    id4 = i     +  j    * nu;

                    V = pts([id1 id2 id3 id4], :);
                    if any(~isfinite(V(:)))
                        continue;
                    end

                    ids = [id1 id2 id3 id4];
                    ids = geom.MeshWriter.orientCellWithNormals(mesh, ids);

                    quads(end+1,:) = offset0 + (ids - 1); %#ok<AGROW>
                end
            end
        end

        function ids = orientCellWithNormals(mesh, ids)
            if ~isfield(mesh, 'normals') || isempty(mesh.normals)
                return;
            end

            pts = [mesh.X(:), mesh.Y(:), mesh.Z(:)];
            nrms = reshape(mesh.normals, [], 3);

            V = pts(ids, :);
            N = nrms(ids, :);
            keep = all(isfinite(N), 2);

            if ~any(keep)
                return;
            end

            navg = mean(N(keep, :), 1);
            nrm = norm(navg);
            if nrm < eps
                return;
            end
            navg = navg / nrm;

            ncell = cross(V(2,:) - V(1,:), V(3,:) - V(1,:));
            nrm2 = norm(ncell);
            if nrm2 < eps
                return;
            end
            ncell = ncell / nrm2;

            if dot(ncell, navg) < 0
                ids = [ids(1), ids(4), ids(3), ids(2)];
            end
        end

        function tf = isCollapsedEdge(P, tol)
            if nargin < 2 || isempty(tol)
                tol = 1e-12;
            end
            if isempty(P)
                tf = true;
                return;
            end
            tf = max(vecnorm(P - P(1,:), 2, 2)) <= tol;
        end

        function L = edgeArcLength(P)
            if size(P,1) < 2
                L = 0;
                return;
            end
            L = sum(vecnorm(diff(P,1,1), 2, 2));
        end


        function idx = findEdgeRecordIndex(edges, netName, edgeName)
            idx = [];
            targetNet = upper(strtrim(char(netName)));
            targetEdge = upper(strtrim(char(edgeName)));
            for k = 1:numel(edges)
                if strcmpi(edges(k).netName, targetNet) && strcmpi(edges(k).edgeName, targetEdge)
                    idx = k;
                    return;
                end
            end
            error('MeshWriter.findEdgeRecordIndex: edge %s %s not found.', char(netName), char(edgeName));
        end

        function idx = findNetworkByName(networks, name)
            idx = [];
            target = upper(strtrim(char(name)));
            for k = 1:numel(networks)
                thisName = geom.MeshWriter.getNetworkName(networks{k}, k);
                if strcmpi(thisName, target)
                    idx = k;
                    return;
                end
            end
            error('MeshWriter.findNetworkByName: network "%s" not found.', char(name));
        end

        function name = getNetworkName(net, k)
            if nargin < 2
                k = 1;
            end
            if isfield(net, 'name') && ~isempty(net.name)
                name = char(net.name);
            else
                name = sprintf('Network_%d', k);
            end
            name = upper(strtrim(name));
        end

        function [n, area2] = triNormal(V1, V2, V3)
            e1 = V2 - V1;
            e2 = V3 - V1;
            n = cross(e1, e2);
            area2 = norm(n);
            if area2 > eps
                n = n / area2;
            else
                n = [0 0 0];
            end
        end
    end
end